project:
  type: website
  output-dir: docs

website:
  title: "Data Acquisition blog"
  description: "A quick example of webscraping and data cleaning"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.html
      - text: "Blog"
        href: blog.html
    right:
      - icon: github
        href: https://github.com/Eric-Coons
        
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css